services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: junior
      POSTGRES_PASSWORD: junior
      POSTGRES_DB: crud_node
    ports:
      - "5456:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U junior -d crud_node"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://junior:junior@db:5432/crud_node?schema=public
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
